#!/usr/bin/env bash
# generate-briefing.sh — compose a memory-powered morning briefing for an OpenClaw agent.
# Clean-room Rin implementation: pulls deterministic data from the agent's own memory stack.
# The agent fills the Memory-surfacing line with mdeep (total recall).
# Usage: ./generate-briefing.sh [/path/to/workspace] [--short]   (--short skips health + schedule)
set -uo pipefail

SHORT=false; WS=""
for a in "$@"; do
  case "$a" in
    --short) SHORT=true ;;
    -h|--help) sed -n '2,5p' "$0"; exit 0 ;;
    *) WS="$a" ;;
  esac
done
WS="${WS:-${OPENCLAW_WORKSPACE:-$HOME/.openclaw/workspace}}"
M="$WS/memory"
[[ -d "$WS" ]] || { echo "workspace not found: $WS" >&2; exit 1; }

have(){ [[ -s "$1" ]]; }
body(){ awk '/^---[[:space:]]*$/{f++;next} f!=1{print}' "$1" 2>/dev/null; }   # strip leading YAML frontmatter
sect(){ printf '\n## %s\n' "$1"; }

echo "# Morning Briefing — $(date -u +%Y-%m-%d)"
echo "_Memory-powered. Under 2 min: focus, then act._"

sect "Focus today"
foc=$(have "$M/active-tasks.md" && grep -m1 -E '^#{1,2} ' "$M/active-tasks.md" | sed 's/^#* *//')
echo "- ${foc:-Set the top open loop and move it forward.}"

sect "Where we left off"
if have "$M/last-conversation.md"; then body "$M/last-conversation.md" | grep -vE '^[[:space:]]*$' | head -3 | sed 's/^/- /'
else echo "- (no continuity note)"; fi

sect "Pending"
if have "$M/active-tasks.md"; then
  grep -E '^#{1,3} ' "$M/active-tasks.md" | sed 's/^#* *//' | grep -viE '^location' | head -5 | sed 's/^/- /'
else echo "- (no tasks file)"; fi

sect "Memory surfacing"
# Auto-surface "forgotten but important" memories from the decay signal (model-free);
# fall back to the manual mdeep nudge if node / surface.mjs is unavailable.
SURFACE_JS="$WS/scripts/semantic/surface.mjs"
if command -v node >/dev/null 2>&1 && [[ -f "$SURFACE_JS" ]]; then
  surf=$(node "$SURFACE_JS" --top 3 --ws "$WS" 2>/dev/null)
else
  surf=""
fi
if [[ -n "$surf" && "$surf" != "(nothing to resurface)" ]]; then
  echo "$surf"
else
  printf -- '- [agent: run  mdeep "<topic from current focus>" 4  and surface ONE relevant past detail/decision the human may have forgotten]\n'
fi

sect "Recently learned"
learned=$( { have "$M/learnings.md" && body "$M/learnings.md" | grep -m1 -E '^#{2,3} |^- ' | sed 's/^#* *//'; } )
[[ -z "$learned" ]] && learned=$( have "$M/curator-log.md" && tail -5 "$M/curator-log.md" | grep -m1 '[A-Za-z]' )
echo "- ${learned:-(nothing new logged)}"

if ! $SHORT; then
  sect "System health"
  if have "$M/health-monitor.log"; then
    h=$(tail -8 "$M/health-monitor.log" | grep -iE 'ok|healthy|critical|warn|alert' | tail -1)
    echo "- ${h:-(health log present; no recent status line)}"
  else echo "- (no health log)"; fi
  if command -v free >/dev/null 2>&1; then
    free -m 2>/dev/null | awk '/^Mem:/{printf "- mem: %dMB used / %dMB available\n",$3,$7}'
  else
    echo "- mem: (unavailable on this OS)"
  fi

  sect "Scheduled today"
  jobs=$(crontab -l 2>/dev/null | grep -E '^[0-9*]' | sed 's/ *>>.*//; s/ *2>&1.*//' | cut -c1-72)
  if [[ -n "$jobs" ]]; then echo "$jobs" | head -6 | sed 's/^/- /'; else echo "- (no cron jobs)"; fi
fi

printf '\n_Generated by morning-briefing. Keep it to 15 bullets max._\n'
